using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace QL_DatTiecNhaHang
{
    public partial class DishComboForm : DevExpress.XtraEditors.XtraForm
    {
        public DishComboForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            combO_MONANTableAdapter1.Fill(qlDatTiecNhaHangDataSet1.COMBO_MONAN);
        }

        private void DishComboForm_Load(object sender, EventArgs e)
        {

        }
    }
}