using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace QL_DatTiecNhaHang
{
    public partial class DishForm : DevExpress.XtraEditors.XtraForm
    {

        private string idMA;
        private bool isAdd = false;

        public DishForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            monanTableAdapter1.Fill(qlDatTiecNhaHangDataSet1.MONAN);
        }

        private void DishForm_Load(object sender, EventArgs e)
        {

        }

        private void loadDB()
        {
            monanTableAdapter1.Fill(qlDatTiecNhaHangDataSet1.MONAN);
            //btnLuu.Enabled = false;

        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {

            // do dl len textbox
            textEdit1.Text = gridView1.GetRowCellValue(e.FocusedRowHandle, "TenMA").ToString();
            textEdit5.Text = gridView1.GetRowCellValue(e.FocusedRowHandle, "GhiChu").ToString();
            //idMA = gridView1.GetRowCellValue(e.FocusedRowHandle, "IdMA").ToString();
            
        }

        private void simpleButton2_Click(object sender, EventArgs e)//thêm
        {
            isAdd = true;
            ClearTextBox();
            textEdit1.Focus();
        }

        private void ClearTextBox()
        {
            Action<Control.ControlCollection> func = null;

            func = (controls) =>
            {
                foreach (Control control in controls)
                    if (control is TextBox)
                        (control as TextBox).Clear();
                    else
                        func(control.Controls);
            };

            func(Controls);
        }

        private void simpleButton4_Click(object sender, EventArgs e)//xóa
        {
            if (XtraMessageBox.Show(MessageBoxConst.DELETE_CONFIRM, MessageBoxConst.NOTIFICATION,
                MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button2)
                == DialogResult.No)
                return;

            try
            {
                monanTableAdapter1.Delete(int.Parse(idMA));
                XtraMessageBox.Show(MessageBoxConst.DELETED_SUCCESSFULLY, MessageBoxConst.NOTIFICATION, MessageBoxButtons.OK, MessageBoxIcon.Information);
                loadDB();
            }
            catch
            {
                XtraMessageBox.Show(MessageBoxConst.ERROR_WHEN_DELETE_VALUE, MessageBoxConst.ERROR, MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

       
    }
}