using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace QL_DatTiecNhaHang
{
    public partial class EmployeeForm : DevExpress.XtraEditors.XtraForm
    {

        private string idNV;
        private bool isAdd = false;

        public EmployeeForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            loadDB();
        }

        private void EmployeeForm_Load(object sender, EventArgs e)
        {

        }

        private void loadDB()
        {
            nhanvienTableAdapter1.Fill(qlDatTiecNhaHangDataSet1.NHANVIEN);
        }

        private void simpleButton2_Click(object sender, EventArgs e)//them
        {
            isAdd = true;
            ClearTextBox();
            textEdit1.Focus();
        }



        private void ClearTextBox()
        {
            Action<Control.ControlCollection> func = null;

            func = (controls) =>
            {
                foreach (Control control in controls)
                    if (control is TextBox)
                        (control as TextBox).Clear();
                    else
                        func(control.Controls);
            };

            func(Controls);
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            if (XtraMessageBox.Show(MessageBoxConst.DELETE_CONFIRM, MessageBoxConst.NOTIFICATION,
                MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button2)
                == DialogResult.No)
                return;

            try
            {
                nhanvienTableAdapter1.Delete(int.Parse(idNV));
                XtraMessageBox.Show(MessageBoxConst.DELETED_SUCCESSFULLY, MessageBoxConst.NOTIFICATION, MessageBoxButtons.OK, MessageBoxIcon.Information);
                loadDB();
            }
            catch
            {
                XtraMessageBox.Show(MessageBoxConst.ERROR_WHEN_DELETE_VALUE, MessageBoxConst.ERROR, MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
}