//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class BOPHAN : XPLiteObject
    {
        int fIdBP;
        [Key(true)]
        public int IdBP
        {
            get { return fIdBP; }
            set { SetPropertyValue<int>(nameof(IdBP), ref fIdBP, value); }
        }
        string fTenBP;
        [Size(50)]
        public string TenBP
        {
            get { return fTenBP; }
            set { SetPropertyValue<string>(nameof(TenBP), ref fTenBP, value); }
        }
        string fGhiChu;
        [Size(SizeAttribute.Unlimited)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        [Association(@"NHANVIENReferencesBOPHAN")]
        public XPCollection<NHANVIEN> NHANVIENs { get { return GetCollection<NHANVIEN>(nameof(NHANVIENs)); } }
    }

}
