//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class COMBO_MONAN : XPLiteObject
    {
        int fIdCBMA;
        [Key(true)]
        public int IdCBMA
        {
            get { return fIdCBMA; }
            set { SetPropertyValue<int>(nameof(IdCBMA), ref fIdCBMA, value); }
        }
        string fGhiChu;
        [Size(SizeAttribute.Unlimited)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        [Association(@"DATTIECReferencesCOMBO_MONAN")]
        public XPCollection<DATTIEC> DATTIECs { get { return GetCollection<DATTIEC>(nameof(DATTIECs)); } }
    }

}
