//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(BOPHAN),
            typeof(COMBO_MONAN),
            typeof(CT_DT_DU),
            typeof(CT_DT_DV),
            typeof(CT_DT_MA),
            typeof(CT_DT_NV),
            typeof(CT_DT_ST),
            typeof(CT_MA_CBMA),
            typeof(CT_ND_NND),
            typeof(CT_PHATSINH),
            typeof(DATTIEC),
            typeof(DICHVU),
            typeof(DODUNG),
            typeof(DOUONG),
            typeof(HOADON),
            typeof(KHACHHANG),
            typeof(LOAIDOUONG),
            typeof(LOAIMONAN),
            typeof(LOAITIEC),
            typeof(MANHINH),
            typeof(MONAN),
            typeof(NGUOIDUNG),
            typeof(NHANVIEN),
            typeof(NHOMNGUOIDUNG),
            typeof(PHANQUYEN),
            typeof(SANHTIEC),
            typeof(SYSDIAGRAMS)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        static Type[] nonPersistentTypes = new Type[] {
            typeof(BOPHAN_InsResult),
            typeof(BOPHAN_UpdResult),
            typeof(DANGNHAPResult),
            typeof(DICHVU_UpdResult),
            typeof(BOPHAN_InsResult1),
            typeof(BOPHAN_UpdResult1),
            typeof(DICHVU_UpdResult1),
            typeof(DODUNG_InsResult),
            typeof(DODUNG_UpdResult),
            typeof(DOUONG_InsResult),
            typeof(LOAIDOUONG_InsResult),
            typeof(LOAIDOUONG_UpdResult),
            typeof(LOAIMONAN_UpdResult),
            typeof(LOAIMONAN_InsResult),
            typeof(LOAITIEC_InsResult),
            typeof(LOAITIEC_UpdResult),
            typeof(MANHINH_InsResult),
            typeof(MANHINH_UpdResult),
            typeof(MONAN_DelResult),
            typeof(NHANVIEN_ByIdResult),
            typeof(BOPHAN_InsResult2),
            typeof(BOPHAN_UpdResult2),
            typeof(DICHVU_UpdResult2),
            typeof(DODUNG_InsResult1),
            typeof(DODUNG_UpdResult1),
            typeof(DOUONG_InsResult1),
            typeof(LOAIDOUONG_InsResult1),
            typeof(LOAIDOUONG_UpdResult1),
            typeof(LOAIMONAN_UpdResult1),
            typeof(LOAIMONAN_InsResult1),
            typeof(LOAITIEC_InsResult1),
            typeof(LOAITIEC_UpdResult1),
            typeof(MANHINH_InsResult1),
            typeof(MANHINH_UpdResult1),
            typeof(MONAN_DelResult1),
            typeof(KHACHHANG_GetAllResult)
        };
        public static Type[] GetNonPersistentTypes()
        {
            Type[] copy = new Type[nonPersistentTypes.Length];
            Array.Copy(nonPersistentTypes, copy, nonPersistentTypes.Length);
            return copy;
        }
        public static string ConnectionString { get { return System.Configuration.ConfigurationManager.ConnectionStrings["DESKTOP-TC830C5_QLDatTiecNhaHang"].ConnectionString; } }
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                dictionary.CollectClassInfos(nonPersistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
