//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class CT_DT_DU : XPLiteObject
    {
        int fSL_DU;
        public int SL_DU
        {
            get { return fSL_DU; }
            set { SetPropertyValue<int>(nameof(SL_DU), ref fSL_DU, value); }
        }
        int fSL_DU_PS;
        public int SL_DU_PS
        {
            get { return fSL_DU_PS; }
            set { SetPropertyValue<int>(nameof(SL_DU_PS), ref fSL_DU_PS, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("IdDT")]
            public int IdDT { get; set; }
            [Persistent("IdDU")]
            public int IdDU { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
