//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class DICHVU : XPLiteObject
    {
        int fIdDV;
        [Key]
        public int IdDV
        {
            get { return fIdDV; }
            set { SetPropertyValue<int>(nameof(IdDV), ref fIdDV, value); }
        }
        string fTenDV;
        [Size(200)]
        public string TenDV
        {
            get { return fTenDV; }
            set { SetPropertyValue<string>(nameof(TenDV), ref fTenDV, value); }
        }
        decimal fDonGiaDV;
        public decimal DonGiaDV
        {
            get { return fDonGiaDV; }
            set { SetPropertyValue<decimal>(nameof(DonGiaDV), ref fDonGiaDV, value); }
        }
        string fGhiChu;
        [Size(SizeAttribute.Unlimited)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        [Association(@"CT_PHATSINHReferencesDICHVU")]
        public XPCollection<CT_PHATSINH> CT_PHATSINHs { get { return GetCollection<CT_PHATSINH>(nameof(CT_PHATSINHs)); } }
    }

}
