//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class DOUONG : XPLiteObject
    {
        int fIdDU;
        [Key(true)]
        public int IdDU
        {
            get { return fIdDU; }
            set { SetPropertyValue<int>(nameof(IdDU), ref fIdDU, value); }
        }
        string fTenDU;
        [Size(200)]
        public string TenDU
        {
            get { return fTenDU; }
            set { SetPropertyValue<string>(nameof(TenDU), ref fTenDU, value); }
        }
        string fDVT;
        [Size(10)]
        public string DVT
        {
            get { return fDVT; }
            set { SetPropertyValue<string>(nameof(DVT), ref fDVT, value); }
        }
        decimal fDonGia;
        public decimal DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
        decimal fDonGia_PS;
        public decimal DonGia_PS
        {
            get { return fDonGia_PS; }
            set { SetPropertyValue<decimal>(nameof(DonGia_PS), ref fDonGia_PS, value); }
        }
        string fGhiChu;
        [Size(SizeAttribute.Unlimited)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        LOAIDOUONG fIdLDU;
        [Association(@"DOUONGReferencesLOAIDOUONG")]
        public LOAIDOUONG IdLDU
        {
            get { return fIdLDU; }
            set { SetPropertyValue<LOAIDOUONG>(nameof(IdLDU), ref fIdLDU, value); }
        }
        [Association(@"CT_PHATSINHReferencesDOUONG")]
        public XPCollection<CT_PHATSINH> CT_PHATSINHs { get { return GetCollection<CT_PHATSINH>(nameof(CT_PHATSINHs)); } }
    }

}
