//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    [NonPersistent]
    public partial class KHACHHANG_GetAllResult
    {
        public string HoTenKH { get; set; }
        public string NgaySinhKH { get; set; }
        public bool GioiTinhKH { get; set; }
        public string DiaChiKH { get; set; }
        public string DienThoaiKH { get; set; }
        public string EmailKH { get; set; }
        public string GhiChu { get; set; }
    }

}
