//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class LOAIMONAN : XPLiteObject
    {
        int fIdLMA;
        [Key(true)]
        public int IdLMA
        {
            get { return fIdLMA; }
            set { SetPropertyValue<int>(nameof(IdLMA), ref fIdLMA, value); }
        }
        string fTenLMA;
        [Size(50)]
        public string TenLMA
        {
            get { return fTenLMA; }
            set { SetPropertyValue<string>(nameof(TenLMA), ref fTenLMA, value); }
        }
        string fGhiChu;
        [Size(SizeAttribute.Unlimited)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        [Association(@"MONANReferencesLOAIMONAN")]
        public XPCollection<MONAN> MONANs { get { return GetCollection<MONAN>(nameof(MONANs)); } }
    }

}
