//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class MANHINH : XPLiteObject
    {
        int fIdMH;
        [Key(true)]
        public int IdMH
        {
            get { return fIdMH; }
            set { SetPropertyValue<int>(nameof(IdMH), ref fIdMH, value); }
        }
        string fTenMH;
        [Size(50)]
        public string TenMH
        {
            get { return fTenMH; }
            set { SetPropertyValue<string>(nameof(TenMH), ref fTenMH, value); }
        }
    }

}
