//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class NGUOIDUNG : XPLiteObject
    {
        string fTenDangNhap;
        [Key]
        [Size(16)]
        public string TenDangNhap
        {
            get { return fTenDangNhap; }
            set { SetPropertyValue<string>(nameof(TenDangNhap), ref fTenDangNhap, value); }
        }
        string fMatKhau;
        [Size(16)]
        public string MatKhau
        {
            get { return fMatKhau; }
            set { SetPropertyValue<string>(nameof(MatKhau), ref fMatKhau, value); }
        }
        bool fHoatDong;
        public bool HoatDong
        {
            get { return fHoatDong; }
            set { SetPropertyValue<bool>(nameof(HoatDong), ref fHoatDong, value); }
        }
        NHANVIEN fIdNV;
        [Indexed(Name = @"IDNV", Unique = true)]
        [Association(@"NGUOIDUNGReferencesNHANVIEN")]
        public NHANVIEN IdNV
        {
            get { return fIdNV; }
            set { SetPropertyValue<NHANVIEN>(nameof(IdNV), ref fIdNV, value); }
        }
    }

}
