//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    [NonPersistent]
    public partial class NHANVIEN_ByIdResult
    {
        public int IdNV { get; set; }
        public string HoTenNV { get; set; }
        public DateTime NgaySinhNV { get; set; }
        public bool GioiTinhNV { get; set; }
        public string DiaChiNV { get; set; }
        public string DienThoaiNV { get; set; }
        public string GhiChuNV { get; set; }
        public string TenBP { get; set; }
    }

}
