//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class NHANVIEN : XPLiteObject
    {
        int fIdNV;
        [Key(true)]
        public int IdNV
        {
            get { return fIdNV; }
            set { SetPropertyValue<int>(nameof(IdNV), ref fIdNV, value); }
        }
        string fHoTenNV;
        public string HoTenNV
        {
            get { return fHoTenNV; }
            set { SetPropertyValue<string>(nameof(HoTenNV), ref fHoTenNV, value); }
        }
        DateTime fNgaySinhNV;
        public DateTime NgaySinhNV
        {
            get { return fNgaySinhNV; }
            set { SetPropertyValue<DateTime>(nameof(NgaySinhNV), ref fNgaySinhNV, value); }
        }
        bool fGioiTinhNV;
        public bool GioiTinhNV
        {
            get { return fGioiTinhNV; }
            set { SetPropertyValue<bool>(nameof(GioiTinhNV), ref fGioiTinhNV, value); }
        }
        string fDiaChiNV;
        [Size(500)]
        public string DiaChiNV
        {
            get { return fDiaChiNV; }
            set { SetPropertyValue<string>(nameof(DiaChiNV), ref fDiaChiNV, value); }
        }
        string fDienThoaiNV;
        [Size(10)]
        public string DienThoaiNV
        {
            get { return fDienThoaiNV; }
            set { SetPropertyValue<string>(nameof(DienThoaiNV), ref fDienThoaiNV, value); }
        }
        string fGhiChuNV;
        [Size(SizeAttribute.Unlimited)]
        public string GhiChuNV
        {
            get { return fGhiChuNV; }
            set { SetPropertyValue<string>(nameof(GhiChuNV), ref fGhiChuNV, value); }
        }
        BOPHAN fIdBP;
        [Association(@"NHANVIENReferencesBOPHAN")]
        public BOPHAN IdBP
        {
            get { return fIdBP; }
            set { SetPropertyValue<BOPHAN>(nameof(IdBP), ref fIdBP, value); }
        }
        [Association(@"NGUOIDUNGReferencesNHANVIEN")]
        public XPCollection<NGUOIDUNG> NGUOIDUNGs { get { return GetCollection<NGUOIDUNG>(nameof(NGUOIDUNGs)); } }
    }

}
