//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class NHOMNGUOIDUNG : XPLiteObject
    {
        int fIdNND;
        [Key(true)]
        public int IdNND
        {
            get { return fIdNND; }
            set { SetPropertyValue<int>(nameof(IdNND), ref fIdNND, value); }
        }
        string fTenNND;
        public string TenNND
        {
            get { return fTenNND; }
            set { SetPropertyValue<string>(nameof(TenNND), ref fTenNND, value); }
        }
    }

}
