//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{

    public partial class PHANQUYEN : XPLiteObject
    {
        bool fCoQuyen;
        public bool CoQuyen
        {
            get { return fCoQuyen; }
            set { SetPropertyValue<bool>(nameof(CoQuyen), ref fCoQuyen, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("IdNND")]
            public int IdNND { get; set; }
            [Persistent("IdMH")]
            public int IdMH { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
