//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QL_DatTiecNhaHang.QLDatTiecNhaHang
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData ExecBOPHAN_Del(Session session, int IdBP)
        {
            return session.ExecuteSproc("BOPHAN_Del", new OperandValue(IdBP));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecBOPHAN_Ins(Session session, string TenBP, string GhiChu)
        {
            return session.ExecuteSproc("BOPHAN_Ins", new OperandValue(TenBP), new OperandValue(GhiChu));
        }
        public static System.Collections.Generic.ICollection<BOPHAN_InsResult> ExecBOPHAN_InsIntoObjects(Session session, string TenBP, string GhiChu)
        {
            return session.GetObjectsFromSproc<BOPHAN_InsResult>("BOPHAN_Ins", new OperandValue(TenBP), new OperandValue(GhiChu));
        }
        public static XPDataView ExecBOPHAN_InsIntoDataView(Session session, string TenBP, string GhiChu)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("BOPHAN_Ins", new OperandValue(TenBP), new OperandValue(GhiChu));
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(BOPHAN_InsResult)), sprocData);
        }
        public static void ExecBOPHAN_InsIntoDataView(XPDataView dataView, Session session, string TenBP, string GhiChu)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("BOPHAN_Ins", new OperandValue(TenBP), new OperandValue(GhiChu));
            dataView.PopulateProperties(session.GetClassInfo(typeof(BOPHAN_InsResult)));
            dataView.LoadData(sprocData);
        }
        public static DevExpress.Xpo.DB.SelectedData ExecBOPHAN_Upd(Session session, int IdBP, string TenBP, string GhiChu)
        {
            return session.ExecuteSproc("BOPHAN_Upd", new OperandValue(IdBP), new OperandValue(TenBP), new OperandValue(GhiChu));
        }
        public static System.Collections.Generic.ICollection<BOPHAN_UpdResult> ExecBOPHAN_UpdIntoObjects(Session session, int IdBP, string TenBP, string GhiChu)
        {
            return session.GetObjectsFromSproc<BOPHAN_UpdResult>("BOPHAN_Upd", new OperandValue(IdBP), new OperandValue(TenBP), new OperandValue(GhiChu));
        }
        public static XPDataView ExecBOPHAN_UpdIntoDataView(Session session, int IdBP, string TenBP, string GhiChu)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("BOPHAN_Upd", new OperandValue(IdBP), new OperandValue(TenBP), new OperandValue(GhiChu));
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(BOPHAN_UpdResult)), sprocData);
        }
        public static void ExecBOPHAN_UpdIntoDataView(XPDataView dataView, Session session, int IdBP, string TenBP, string GhiChu)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("BOPHAN_Upd", new OperandValue(IdBP), new OperandValue(TenBP), new OperandValue(GhiChu));
            dataView.PopulateProperties(session.GetClassInfo(typeof(BOPHAN_UpdResult)));
            dataView.LoadData(sprocData);
        }
        public static DevExpress.Xpo.DB.SelectedData ExecDANGNHAP(Session session, string TenDangNhap, string MatKhau)
        {
            return session.ExecuteSproc("DANGNHAP", new OperandValue(TenDangNhap), new OperandValue(MatKhau));
        }
        public static System.Collections.Generic.ICollection<DANGNHAPResult> ExecDANGNHAPIntoObjects(Session session, string TenDangNhap, string MatKhau)
        {
            return session.GetObjectsFromSproc<DANGNHAPResult>("DANGNHAP", new OperandValue(TenDangNhap), new OperandValue(MatKhau));
        }
        public static XPDataView ExecDANGNHAPIntoDataView(Session session, string TenDangNhap, string MatKhau)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("DANGNHAP", new OperandValue(TenDangNhap), new OperandValue(MatKhau));
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(DANGNHAPResult)), sprocData);
        }
        public static void ExecDANGNHAPIntoDataView(XPDataView dataView, Session session, string TenDangNhap, string MatKhau)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("DANGNHAP", new OperandValue(TenDangNhap), new OperandValue(MatKhau));
            dataView.PopulateProperties(session.GetClassInfo(typeof(DANGNHAPResult)));
            dataView.LoadData(sprocData);
        }
        public static DevExpress.Xpo.DB.SelectedData ExecDICHVU_Del(Session session, int IdDV)
        {
            return session.ExecuteSproc("DICHVU_Del", new OperandValue(IdDV));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecDICHVU_Upd(Session session, int IdDV, string TenDV, decimal DonGiaDV, string GhiChu)
        {
            return session.ExecuteSproc("DICHVU_Upd", new OperandValue(IdDV), new OperandValue(TenDV), new OperandValue(DonGiaDV), new OperandValue(GhiChu));
        }
        public static System.Collections.Generic.ICollection<DICHVU_UpdResult> ExecDICHVU_UpdIntoObjects(Session session, int IdDV, string TenDV, decimal DonGiaDV, string GhiChu)
        {
            return session.GetObjectsFromSproc<DICHVU_UpdResult>("DICHVU_Upd", new OperandValue(IdDV), new OperandValue(TenDV), new OperandValue(DonGiaDV), new OperandValue(GhiChu));
        }
        public static XPDataView ExecDICHVU_UpdIntoDataView(Session session, int IdDV, string TenDV, decimal DonGiaDV, string GhiChu)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("DICHVU_Upd", new OperandValue(IdDV), new OperandValue(TenDV), new OperandValue(DonGiaDV), new OperandValue(GhiChu));
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(DICHVU_UpdResult)), sprocData);
        }
        public static void ExecDICHVU_UpdIntoDataView(XPDataView dataView, Session session, int IdDV, string TenDV, decimal DonGiaDV, string GhiChu)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("DICHVU_Upd", new OperandValue(IdDV), new OperandValue(TenDV), new OperandValue(DonGiaDV), new OperandValue(GhiChu));
            dataView.PopulateProperties(session.GetClassInfo(typeof(DICHVU_UpdResult)));
            dataView.LoadData(sprocData);
        }
    }
}
